// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlajztdniithszkezavx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsYWp6dGRuaWl0aHN6a2V6YXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjA3MjgsImV4cCI6MjA2NDQzNjcyOH0.mUS88re80LnnpwQ2JXLYbYaw3irrRLqw2CPx9NTJpvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);